[package]
version = "0.1.0"
category = "Simulation"
title = "gn10.mid360s"
description = "This is the Extension Simulate Livox Mid-360S in Isaac Sim. The LiDAR output published by a ROS2 PointCloud topic."
authors = ["Gento Aiba"]
repository = ""
keywords = ["gn10", "ROS2", "Mid-360S", "Mid-360", "Livox", "Sensors", "LiDAR"]
changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.experimental.utils" = {}
"isaacsim.core.nodes" = {}
"isaacsim.core.rendering_manager" = {}
"isaacsim.core.simulation_manager" = {}
"isaacsim.examples.browser" = {}
"isaacsim.gui.components" = {}
"isaacsim.ros2.nodes" = {}
"isaacsim.storage.native" = {}
"omni.graph" = {}
"omni.graph.tools" = {}
"omni.replicator.core" = {}
"omni.timeline" = {}
"omni.ui" = {}

[[python.module]]
name = "gn10_mid360s_python"

[fswatcher.patterns]
include = ["*.ogn", "*.py", "*.toml"]
exclude = ["Ogn*Database.py"]

[fswatcher.paths]
exclude = ["*/bin", "*/__pycache__/*", "*/.git/*"]