# SPDX-FileCopyrightText: Copyright (c) 2022-2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0

"""OmniGraph node for the simulated Livox Mid-360S point cloud."""

import numpy as np

from .... import global_variables


class OgnMid360PointCloud:
    """OmniGraph node that outputs the latest Mid-360 point cloud."""

    @staticmethod
    def compute(db) -> bool:
        """Output the latest point cloud generated by OmniPerception."""

        points_tensor = global_variables.latest_points

        if points_tensor is None:
            db.outputs.points = []
            return True

        try:
            points = (
                points_tensor
                .detach()
                .cpu()
                .numpy()
                .reshape(-1, 3)
            )

            valid_mask = (
                ~np.isnan(points).any(axis=1)
                & (np.linalg.norm(points, axis=1) > 0.01)
            )

            points = points[valid_mask]

            db.outputs.points = [
                (
                    float(point[0]),
                    float(point[1]),
                    float(point[2]),
                )
                for point in points
            ]

            return True

        except Exception as e:
            print(f"[Mid360PointCloud] Failed to output point cloud: {e}")

            db.outputs.points = []

            return False